Fix bug caused by semicolon missing
ReferenceError: Cannot access 'extractedIssueBody' before initialization
    at buildIssueBody (/home/runner/work/_actions/noraworld/issue-recorder/main/app.js:177:15)
    at run (/home/runner/work/_actions/noraworld/issue-recorder/main/app.js:54:84)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Process completed with exit code 1.

https://github.com/noraworld/reserved-diary/actions/runs/15720523047/job/44300320409